# Assemble descriptive analysis QMD from outputs
# Combines narrative, tables, and figures with APA captions

library(readr)
library(dplyr)
library(stringr)
library(glue)
library(fs)

qmd_path <- "scripts/eda/01_descriptive_analysis.qmd"

# =============================================================================
# Read inputs
# =============================================================================

narrative <- readLines("output/notes/descriptive_findings_draft.md")
inventory <- readLines("output/notes/apa_inventory.md")

# =============================================================================
# Parse inventory into lookup
# =============================================================================

parse_inventory_block <- function(lines, pattern) {
  results <- list()
  i <- 1
  while (i <= length(lines)) {
    if (str_detect(lines[i], pattern)) {
      title_line <- str_trim(lines[i])
      title_line <- str_remove(title_line, "^###\\s*")

      num <- str_extract(title_line, "^(Table|Figure)\\s+([0-9a-z]+)\\.", group = 2)
      type <- str_extract(title_line, "^(Table|Figure)") |> str_to_lower()
      id <- paste0(type, num)

      caption <- ""
      denom <- ""
      file_path <- ""

      j <- i + 1
      while (j <= length(lines) && !str_detect(lines[j], "^###|^---")) {
        if (str_detect(lines[j], "^\\*\\*Caption\\*\\*:")) {
          caption <- str_remove(lines[j], "^\\*\\*Caption\\*\\*:\\s*")
        }
        if (str_detect(lines[j], "^\\*\\*Denominator note\\*\\*:")) {
          denom <- str_remove(lines[j], "^\\*\\*Denominator note\\*\\*:\\s*")
        }
        if (str_detect(lines[j], "^\\*\\*(Source file|File)\\*\\*:")) {
          file_path <- str_extract(lines[j], "`[^`]+`") |>
            str_remove_all("`")
        }
        j <- j + 1
      }

      results[[id]] <- list(
        title = title_line,
        caption = caption,
        denom = denom,
        path = file_path
      )
      i <- j
    } else {
      i <- i + 1
    }
  }
  results
}

table_info <- parse_inventory_block(inventory, "^### Table")
figure_info <- parse_inventory_block(inventory, "^### Figure")

# =============================================================================
# Helper: build table chunk (uses here::here for project-root paths)
# =============================================================================

build_table_chunk <- function(id, csv_path, info) {
  c(
    glue("**{info$title}**"),
    "",
    glue("*Caption*: {info$caption}"),
    "",
    glue("*Denominator note*: {info$denom}"),
    "",
    "```{r}",
    glue("#| label: {id}"),
    "#| echo: false",
    "#| message: false",
    "#| warning: false",
    "",
    glue('tbl <- readr::read_csv(here::here("{csv_path}"), show_col_types = FALSE)'),
    "knitr::kable(tbl)",
    "```",
    ""
  )
}

# =============================================================================
# Helper: build figure block (paths relative to scripts/eda/)
# =============================================================================

build_figure_block <- function(id, png_path, info) {
 alt_text <- str_replace_all(info$title, '"', "'")
  relative_path <- str_replace(png_path, "^output/", "../../output/")
  c(
    glue("**{info$title}**"),
    "",
    glue("*Caption*: {info$caption}"),
    "",
    glue("*Denominator note*: {info$denom}"),
    "",
    glue('![{info$title}]({relative_path}){{fig-alt="{alt_text}"}}'),
    ""
  )
}

# =============================================================================
# Build QMD content
# =============================================================================

timestamp <- format(Sys.time(), "%Y-%m-%d %H:%M:%S")

qmd_lines <- c(
  "---",
  'title: "ASRS UAS Reports: Descriptive Analysis"',
  "author: \"Generated by 11_assemble_descriptives_qmd.R\"",
  glue("date: \"{Sys.Date()}\""),
  "format:",
  "  html:",
  "    toc: true",
  "    toc-depth: 3",
  "execute:",
  "  echo: false",
  "  warning: false",
  "  message: false",
  "---",
  "",
  "```{r}",
  "#| label: setup",
  "#| include: false",
  'here::i_am("scripts/eda/01_descriptive_analysis.qmd")',
  "```",
  "",
  "# Descriptive Findings",
  "",
  "## Narrative summary",
  "",
  narrative,
  "",
  "---",
  "",
  "## Tables",
  "",
  "The following tables summarize the dataset structure, operational context,",
  "severity markers, and NMAC prevalence patterns.",
  ""
)

table_order <- c("table1", "table2", "table2a", "table3", "table4")
table_paths <- c(
  table1 = "output/tables/table1_overview_completeness.csv",
  table2 = "output/tables/table2_operational_context.csv",
  table2a = "output/tables/table2_optional_crosstabs.csv",
  table3 = "output/tables/table3_severity_markers.csv",
  table4 = "output/tables/table4_nmac_by_context.csv"
)

for (tid in table_order) {
  if (tid %in% names(table_info)) {
    qmd_lines <- c(
      qmd_lines,
      build_table_chunk(tid, table_paths[[tid]], table_info[[tid]]),
      ""
    )
  }
}

qmd_lines <- c(
  qmd_lines,
  "---",
  "",
  "## Figures",
  "",
  "The following figures visualize detection patterns, severity markers,",
  "dominant tags, and NMAC prevalence across operational context.",
  ""
)

figure_order <- c("figure1", "figure2", "figure3", "figure4", "figure5", "figure6")
figure_paths <- c(
  figure1 = "output/figures/fig1_detector_by_phase.png",
  figure2 = "output/figures/fig2_severity_markers_ci.png",
  figure3 = "output/figures/fig3_top_tags.png",
  figure4 = "output/figures/fig4_nmac_by_phase_ci.png",
  figure5 = "output/figures/fig5_nmac_by_detector_ci.png",
  figure6 = "output/figures/fig6_nmac_by_timeblock_ci.png"
)

for (fid in figure_order) {
  if (fid %in% names(figure_info)) {
    qmd_lines <- c(
      qmd_lines,
      build_figure_block(fid, figure_paths[[fid]], figure_info[[fid]]),
      ""
    )
  }
}

qmd_lines <- c(
  qmd_lines,
  "---",
  "",
  "## Reproducibility",
  "",
  "This document was generated from CSV and PNG outputs in `output/`.",
  "",
  glue("**Assembly timestamp**: {timestamp}"),
  "",
  "**Source scripts**:",
  "",
  "- `scripts/eda/01_audit.R` through `scripts/eda/10_build_inventory_captions.R`",
  "- `scripts/eda/11_assemble_descriptives_qmd.R`",
  "",
  "All numeric values in tables are programmatically generated from the",
 "underlying data to ensure consistency and prevent transcription errors.",
  ""
)

# =============================================================================
# Write QMD
# =============================================================================

writeLines(qmd_lines, qmd_path)
cat("Written:", qmd_path, "\n")

n_tables <- length(intersect(table_order, names(table_info)))
n_figures <- length(intersect(figure_order, names(figure_info)))
cat(glue("Assembled: {n_tables} tables, {n_figures} figures\n"))
