# ASRS schema definitions

asrs_expected_cols <- c(
  "acn",
  "time__date",
  "time__local_time_of_day",
  "place__locale_reference",
  "place__state_reference",
  "place__relative_position_angle_radial",
  "place__relative_position_distance_nautical_miles",
  "place__altitude_agl_single_value",
  "place__altitude_msl_single_value",
  "place__latitude_longitude_uas",
  "environment__flight_conditions",
  "environment__weather_elements_visibility",
  "environment__work_environment_factor",
  "environment__light",
  "environment__ceiling",
  "environment__rvr_single_value",
  "ac1__atc_advisory",
  "ac1__aircraft_operator",
  "ac1__make_model_name",
  "ac1__aircraft_zone",
  "ac1__crew_size",
  "ac1__operating_under_far_part",
  "ac1__flight_plan",
  "ac1__mission",
  "ac1__nav_in_use",
  "ac1__flight_phase",
  "ac1__route_in_use",
  "ac1__airspace",
  "ac1__maintenance_status_maintenance_deferred",
  "ac1__maintenance_status_records_complete",
  "ac1__maintenance_status_released_for_service",
  "ac1__maintenance_status_required_correct_doc_on_board",
  "ac1__maintenance_status_maintenance_type",
  "ac1__maintenance_status_maintenance_items_involved",
  "ac1__cabin_lighting",
  "ac1__number_of_seats_number",
  "ac1__passengers_on_board_number",
  "ac1__crew_size_flight_attendant_number_of_crew",
  "ac1__airspace_authorization_provider_uas",
  "ac1__operating_under_waivers_exemptions_authorizations_uas",
  "ac1__waivers_exemptions_authorizations_uas",
  "ac1__airworthiness_certification_uas",
  "ac1__weight_category_uas",
  "ac1__configuration_uas",
  "ac1__flight_operated_as_uas",
  "ac1__flight_operated_with_visual_observer_uas",
  "ac1__control_mode_uas",
  "ac1__flying_in_near_over_uas",
  "ac1__passenger_capable_uas",
  "ac1__type_uas",
  "ac1__number_of_uas_being_controlled_uas",
  "component__aircraft_component",
  "component__manufacturer",
  "component__aircraft_reference",
  "component__problem",
  "ac2__atc_advisory",
  "ac2__aircraft_operator",
  "ac2__make_model_name",
  "ac2__aircraft_zone",
  "ac2__crew_size",
  "ac2__operating_under_far_part",
  "ac2__flight_plan",
  "ac2__mission",
  "ac2__nav_in_use",
  "ac2__flight_phase",
  "ac2__route_in_use",
  "ac2__airspace",
  "ac2__maintenance_status_maintenance_deferred",
  "ac2__maintenance_status_records_complete",
  "ac2__maintenance_status_released_for_service",
  "ac2__maintenance_status_required_correct_doc_on_board",
  "ac2__maintenance_status_maintenance_type",
  "ac2__maintenance_status_maintenance_items_involved",
  "ac2__cabin_lighting",
  "ac2__number_of_seats_number",
  "ac2__passengers_on_board_number",
  "ac2__crew_size_flight_attendant_number_of_crew",
  "ac2__airspace_authorization_provider_uas",
  "ac2__operating_under_waivers_exemptions_authorizations_uas",
  "ac2__waivers_exemptions_authorizations_uas",
  "ac2__airworthiness_certification_uas",
  "ac2__weight_category_uas",
  "ac2__configuration_uas",
  "ac2__flight_operated_as_uas",
  "ac2__flight_operated_with_visual_observer_uas",
  "ac2__control_mode_uas",
  "ac2__flying_in_near_over_uas",
  "ac2__passenger_capable_uas",
  "ac2__type_uas",
  "ac2__number_of_uas_being_controlled_uas",
  "person1__location_of_person",
  "person1__location_in_aircraft",
  "person1__reporter_organization",
  "person1__function",
  "person1__qualification",
  "person1__experience",
  "person1__cabin_activity",
  "person1__human_factors",
  "person1__communication_breakdown",
  "person1__uas_communication_breakdown",
  "person1__asrs_report_number_accession_number",
  "person2__location_of_person",
  "person2__location_in_aircraft",
  "person2__reporter_organization",
  "person2__function",
  "person2__qualification",
  "person2__experience",
  "person2__cabin_activity",
  "person2__human_factors",
  "person2__communication_breakdown",
  "person2__uas_communication_breakdown",
  "person2__asrs_report_number_accession_number",
  "events__anomaly",
  "events__miss_distance",
  "events__were_passengers_involved_in_event",
  "events__detector",
  "events__when_detected",
  "events__result",
  "assessments__contributing_factors_situations",
  "assessments__primary_problem",
  "report1__narrative",
  "report1__callback",
  "report2__narrative",
  "report2__callback",
  "report1__synopsis"
)

asrs_integer_cols <- c(
  "place__relative_position_angle_radial",
  "place__altitude_agl_single_value",
  "place__altitude_msl_single_value",
  "environment__rvr_single_value",
  "ac1__crew_size",
  "ac1__number_of_seats_number",
  "ac1__passengers_on_board_number",
  "ac1__crew_size_flight_attendant_number_of_crew",
  "ac2__crew_size",
  "ac2__number_of_seats_number",
  "ac2__passengers_on_board_number",
  "ac2__crew_size_flight_attendant_number_of_crew"
)

asrs_double_cols <- c("place__relative_position_distance_nautical_miles")

asrs_logical_cols <- c(
  "ac1__maintenance_status_maintenance_deferred",
  "ac1__maintenance_status_records_complete",
  "ac1__maintenance_status_released_for_service",
  "ac1__maintenance_status_required_correct_doc_on_board",
  "ac1__operating_under_waivers_exemptions_authorizations_uas",
  "ac1__flight_operated_with_visual_observer_uas",
  "ac1__passenger_capable_uas",
  "ac2__maintenance_status_maintenance_deferred",
  "ac2__maintenance_status_records_complete",
  "ac2__maintenance_status_released_for_service",
  "ac2__maintenance_status_required_correct_doc_on_board",
  "ac2__operating_under_waivers_exemptions_authorizations_uas",
  "ac2__flight_operated_with_visual_observer_uas",
  "ac2__passenger_capable_uas",
  "events__were_passengers_involved_in_event"
)

asrs_valid_values <- list(
  environment__flight_conditions = c("VMC", "IMC", "Mixed", "Marginal"),
  environment__light = c("Dawn", "Daylight", "Dusk", "Night"),
  time__local_time_of_day = c(
    "0001-0600", "0601-1200", "1201-1800", "1801-2400"
  ),
  ac1__flight_plan = c("None", "VFR", "IFR", "SVFR", "DVFR"),
  ac2__flight_plan = c("None", "VFR", "IFR", "SVFR", "DVFR"),
  ac1__weight_category_uas = c("Micro", "Small", "Medium", "Large"),
  ac2__weight_category_uas = c("Micro", "Small", "Medium", "Large"),
  ac1__configuration_uas = c(
    "Multi-Rotor", "Fixed Wing", "Helicopter", "Hybrid"
  ),
  ac2__configuration_uas = c(
    "Multi-Rotor", "Fixed Wing", "Helicopter", "Hybrid"
  ),
  ac1__flight_operated_as_uas = c("VLOS", "BVLOS"),
  ac2__flight_operated_as_uas = c("VLOS", "BVLOS"),
  component__problem = c("Design", "Failed", "Improperly Operated",
    "Malfunctioning"),
  ac1__cabin_lighting = c("High", "Medium", "Low", "Off"),
  ac2__cabin_lighting = c("High", "Medium", "Low", "Off")
)

asrs_range_bounds <- list(
  place__relative_position_angle_radial = list(0, 360),
  place__altitude_agl_single_value = list(0, Inf),
  place__altitude_msl_single_value = list(-1500, Inf),
  ac1__crew_size = list(0, Inf),
  ac2__crew_size = list(0, Inf)
)

asrs_multi_value_cols <- c(
  "events__anomaly",
  "events__result",
  "assessments__contributing_factors_situations",
  "person1__human_factors",
  "person2__human_factors",
  "ac1__flying_in_near_over_uas",
  "ac2__flying_in_near_over_uas",
  "ac1__mission",
  "ac2__mission"
)

asrs_entity_prefixes <- c(
  "time",
  "place",
  "environment",
  "ac1",
  "ac2",
  "component",
  "person1",
  "person2",
  "events",
  "assessments",
  "report1",
  "report2"
)
